In [1]:
import torch as t
from torch import Tensor
import torch.nn.functional as F

In [19]:
label = F.one_hot(t.arange(0,1), num_classes= 10)
print(label)

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [32]:
print(t.randn(4))

tensor([ 0.8359,  1.2951,  0.8457, -0.6004])


In [33]:
aa= Tensor([3,4,6])
bb = Tensor([1,2,3])
cc = aa+bb
print(cc)
aa[0] = 0
print(cc)

tensor([4., 6., 9.])
tensor([4., 6., 9.])


In [38]:
label1 = F.one_hot(t.arange(2,3), num_classes= 10)
label2 = F.one_hot(t.arange(8,9), num_classes= 10)

cc = t.cat((label1, label2), dim = 0)
print(label1)
print(label2)
print(cc.shape)

tensor([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])
torch.Size([2, 10])


In [60]:
from random import choices
aa_list = [('aaa', 'bbb'), 'bs', 'c', 'd']
print(choices(aa_list, k = 10))

['c', 'd', 'bs', ('aaa', 'bbb'), 'd', 'd', 'd', 'd', ('aaa', 'bbb'), 'bs']
